services:
  mainapp:
    build:
      context: ./mainApp
      dockerfile: Dockerfile
    container_name: mainapp
    restart: always

  vdapp:
    build:
      context: ./vdApp
      dockerfile: Dockerfile
    container_name: vdapp
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - mainapp
      - vdapp
    expose:
      - "80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always