global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'backend'
    static_configs:
      - targets: ['vudip-backend:8000']

  - job_name: 'videocall'
    static_configs:
      - targets: ['vudip-videocall:5173']

  - job_name: 'nginx'
    static_configs:
      - targets: ['vudip-nginx:80']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
